export const MOUNT_CREATE_WORKOUT_FORM = "MOUNT_CREATE_WORKOUT_FORM";
export const MOUNT_EDIT_WORKOUT_FORM = "MOUNT_EDIT_WORKOUT_FORM";
export const MOUNT_FORGOT_PASSWORD_FORM = "MOUNT_FORGOT_PASSWORD_FORM";
export const MOUNT_USER_MENU = "MOUNT_USER_MENU";
export const MOUNT_USER_SETTINGS_FORM = "MOUNT_USER_SETTINGS_FORM";
export const MOUNT_DELETE_ACCOUNT_DIALOGUE = "MOUNT_DELETE_ACCOUNT_DIALOGUE";
export const MOUNT_SPUN_DOWN_SERVER_ALERT = "MOUNT_SPUN_DOWN_SERVER_ALERT";
export const UNMOUNT_ALL_COMPONENTS = "UNMOUNT_ALL_COMPONENTS";
