export const TOGGLE_MOUNT_CREATE_WORKOUT_FORM = "TOGGLE_MOUNT_CREATE_WORKOUT_FORM";
export const TOGGLE_MOUNT_EDIT_WORKOUT_FORM = "TOGGLE_MOUNT_EDIT_WORKOUT_FORM";
export const TOGGLE_MOUNT_FORGOT_PASSWORD_FORM = "TOGGLE_MOUNT_FORGOT_PASSWORD_FORM";
export const TOGGLE_MOUNT_USER_MENU = "TOGGLE_MOUNT_USER_MENU";
export const TOGGLE_MOUNT_USER_SETTINGS_FORM = "TOGGLE_MOUNT_USER_SETTINGS_FORM";
export const TOGGLE_MOUNT_DELETE_ACCOUNT_DIALOGUE = "TOGGLE_MOUNT_DELETE_ACCOUNT_DIALOGUE";
export const TOGGLE_MOUNT_SPUN_DOWN_SERVER_ALERT = "TOGGLE_MOUNT_SPUN_DOWN_SERVER_ALERT";
export const RESET_COMPONENTS_STATE = "RESET_COMPONENTS_STATE";
