export const SET_WORKOUTS = "SET_WORKOUTS";
export const CREATE_WORKOUT = "CREATE_WORKOUT";
export const UPDATE_WORKOUT = "UPDATE_WORKOUT";
export const DELETE_WORKOUT = "DELETE_WORKOUT";
export const RESET_WORKOUTS_STATE = "RESET_WORKOUTS_STATE";