export const SHOW_CREATE_WORKOUT_FORM = "SHOW_CREATE_WORKOUT_FORM";
export const SHOW_EDIT_WORKOUT_FORM = "SHOW_EDIT_WORKOUT_FORM";
export const SHOW_FORGOT_PASSWORD_FORM = "SHOW_FORGOT_PASSWORD_FORM";
export const SHOW_USER_MENU = "SHOW_USER_MENU";
export const SHOW_USER_SETTINGS_FORM = "SHOW_USER_SETTINGS_FORM";
export const SHOW_DELETE_ACCOUNT_DIALOGUE = "SHOW_DELETE_ACCOUNT_DIALOGUE";
export const SHOW_SPUN_DOWN_SERVER_ALERT = "SHOW_SPUN_DOWN_SERVER_ALERT";
export const HIDE_ALL_COMPONENTS = "HIDE_ALL_COMPONENTS";
